[package]
name = "kumanadra-archiving"
description = "Module used for dealing with archived state of Kumandra Protocol"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>", "Kumandrain <kumandrain@koompi.com"]
edition = "2021"
include = [
    "/benches",
    "/src",
    "/Cargo.toml",
]

[dependencies]
merkle_light = { version = "0.4.0", default-features = false }
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive"] }
reed-solomon-erasure = { version = "5.0.3", default-features = false }
serde = { version = "1.0.137", optional = true, features = ["derive"] }
kumandra-core-primitives = { version = "0.1.0", path = "../../k-primitives/core", default-features = false }
thiserror = { version = "1.0.31", optional = true }

# Ugly workaround for https://github.com/rust-lang/cargo/issues/1197
[target.'cfg(any(target_os = "linux", target_os = "macos", all(target_os = "windows", target_env = "gnu")))'.dependencies.sha2]
features = ["asm"]
version = "0.10.2"

# Ugly workaround for https://github.com/rust-lang/cargo/issues/1197
# `asm` feature is not supported on Windows except with GNU toolchain
[target.'cfg(not(any(target_os = "linux", target_os = "macos", all(target_os = "windows", target_env = "gnu"))))'.dependencies.sha2]
default-features = false
version = "0.10.2"

[dev-dependencies]
criterion = "0.3.5"
rand = { version = "0.8.5", features = ["min_const_gen"] }

[features]
default = ["std"]
std = [
    "merkle_light/std",
    "parity-scale-codec/std",
    "reed-solomon-erasure/simd-accel",
    "reed-solomon-erasure/std",
    "serde",
    "sha2/std",
    "kumandra-core-primitives/std",
    "thiserror",
]

[[bench]]
name = "archiving"
harness = false
